@port = {{$dotenv PORT}}
@baseURL = http://localhost:{{port}}

### Search recipes by name
GET {{baseURL}}/api/search?recipeName=Arrabiata

### Add new recipe to overview
POST {{baseURL}}/api/recipes
Content-Type: application/json

{
  "name": "Arrabiata",
  "ingredients": ["penne rigate", 
  "chopped tomatoes", 
  "red chile flakes",
  "garlic"]
}


### Delete recipe from overview
DELETE {{baseURL}}/api/recipes/arrabiata





