@port = {{$dotenv PORT}}
@baseURL = http://localhost:{{port}}

### Search meals by name
GET {{baseURL}}/api/search?mealName=Arrabiata

### Add new recipe to overview
POST {{baseURL}}/api/recipes
Content-Type: application/json

{
  "strMeal": "Pancakes",
  "strIngredient1": "Flour",
  "strIngredient2": "Butter",
  "strIngredient3": "Salt",
  "strIngredient4": "FlourFlour",
  "strIngredient5": "Flour",
  "strIngredient6": "Flour",
  "strIngredient7": "Flour",
  "strMeasure1": "100g",
  "strMeasure2": "1l",
  "strMeasure3": "500g",
  "strMeasure4": "700g",
  "strMeasure5": "600g",
  "strMeasure6": "000g",
  "strMeasure7": "900g",
  "strInstructions": "Put the flour, eggs, milk, 1 tbsp oil and a pinch of salt into a bowl or large jug, then whisk to a smooth batter. Set aside for 30 mins to rest if you have time, or start cooking straight away.\r\nSet a medium frying pan or crêpe pan over a medium heat and carefully wipe it with some oiled kitchen paper. When hot, cook your pancakes for 1 min on each side until golden, keeping them warm in a low oven as you go.\r\nServe with lemon wedges and sugar, or your favourite filling. Once cold, you can layer the pancakes between baking parchment, then wrap in cling film and freeze for up to 2 months."
}


### Get all recipes
GET {{baseURL}}/api/recipes HTTP/1.1
Accept: application/json

### Add new meal
POST {{baseURL}}/api/meals HTTP/1.1
Content-Type: application/json

{
  "name": "Test",
  "ingredient": "pasta"
}

### Get meal
GET {{baseURL}}/api/meals HTTP/1.1






